GET http://localhost:4000/


###

POST http://localhost:3001/api/users/signup
Content-Type: application/json

{
    "firstname":"one",
    "lastname":"one",
    "email":"one@one.com",
    "username":"one",
    "password":"123456"
}


###
GET http://localhost:3001/api/users/

###
Get http://localhost:3001/api/games/?username=one
###
PATCH http://localhost:3001/api/games/?username=one&difficulty=2
###
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "username":"one",
    "password":"123456"
}

###
POST http://localhost:3001/api/games/new
Content-Type: application/json

{
    "username":"one",
    "fullBoard":"[3,2,1]",
    "displayBoard":"[3,2,1]"
}